### ISSUE TITLE
Feat: Unsubscribe from email notifications

### ISSUE THREAD

**Issue by stevem-zhou** [icssc/zotnfound-frontend#21]
## How to find the bug:
- Check email, there are no methods of unsubscribing from newsletter

## Why is this:
- We haven’t implemented any type of checking before sending out emails through nodemailer, everyone right now is currently receiving emails

## How to fix:
- There is a new column called “subscription” in the leaderboard table with default value of true
- With this in mind, add a new option to select under the profile which is in `Home.jsx`:
  - this new option will pop up a modal that will prompt the user to decide whether or not to turn on/of the subscription
![image](https://github.com/icssc/zotnfound-frontend/assets/103971251/9d93e657-7247-46eb-8d54-7667d27f1e6b)

- Also add some text in the email html template which is in the backend repo (`emailTemplate` --> `index.html`) that has a link that will lead the user to set their description to false
![image](https://github.com/icssc/zotnfound-frontend/assets/103971251/fddf9cbe-b618-4140-8a7d-e8c91db78878)

## Resources:
- [ZotNFound - DB Model](https://docs.google.com/document/d/11GNnXQYPDEzKQxUpPGkIm2GcPo4yAJErI0awGnJYpVE/edit?usp=sharing)

**Comment by tyleryy** [comment]
Do I need access to the Firebase project to complete this issue? I would like to see the database tables

**Comment by stevem-zhou** [comment]
> Do I need access to the Firebase project to complete this issue? I would like to see the database tables

You don't need the Firebase project to complete this. To see the database table, you can use pgAdmin with the .env info, or Postman and use a get request on the leaderboard to see the data that it gives back or also the DB document in our ZotnFound drive! Let me know if you need anything else =D

**Comment by tyleryy** [comment]
Where and when do you send emails? Is it when a new item is placed? So is it called in the create new items route? And also what causes the emails to be sent out to everyone? Do you query all the users and call `sendEmail` on each? I think filtering the list off one query retrieving all users who are subscribed be the best approach because if we did at the user level we would have to call a query for each user.

**Comment by NwinNwin** [comment]
Yes you're correct! We send email in backend when a new item is created. We query all user email in leaderboard table to send to everyone in it.

- in backend, under `POST /items`
<img width="742" alt="image" src="https://github.com/icssc/zotnfound-frontend/assets/93059380/83b65211-b1f3-4d13-9198-e4af78018eff">

- NOTE:`nearbyItems` is the email in leaderboard, we should rename it!

**Comment by tyleryy** [comment]
Ooh ic ic, thank you! I completely missed it cause of the `nearbyItems` name lol.
