### ISSUE TITLE
Missing Fly image

### ISSUE THREAD

**Issue by tyleryy** [icssc/zotnfound-frontend#24]
For the `Marker` component in `Map.tsx`, there is no "flyimg." At least, I don't see one.

<img width="1728" alt="Screen Shot 2024-01-16 at 9 58 39 PM" src="https://github.com/icssc/zotnfound-frontend/assets/66880934/ba5ee256-3674-4657-8724-3c31d602fa10">

**Comment by NwinNwin** [comment]
Hi Tyler, Leaflet's fly animation function requires a marker to be displayed upon completing the animation. As we already have an item marker image, we don't want another one that would overlap it. To resolve this issue, I've implemented a workaround by adding a 1-pixel image. This activate the fly animation when a marker or a card is clicked, without hiding the original marker image.

**Comment by tyleryy** [comment]
ah kk that makes sense!
