### ISSUE TITLE
Refactor Map.jsx

### ISSUE THREAD

**Issue by stevem-zhou** [icssc/zotnfound-frontend#4]
## Instructions
- Refactor `Map.jsx` under `src/components/Map`

## Acceptance Criteria
- Move any useState, Variables definition to the top of React Component
- Rename Test function to something more descriptive
- Refactor HandleSubmit, utilize `ApiUtils.js` for API calls

## Notes
Steps to Run React on your computer:
- Clone the Frontend & Backend repos into 1 folder
- `npm install` on both
- `npm start` on both

Map will be on homepage, but there is also another map that shows up when posting an item. 
Follow instructions below to see this map:
- Run your frontend + backend localhost
- Sign In to ZotNFound with UCI email
- Press on `List an Item`
- Go through the steps posting an item
- Marker will appear on map

![image](https://github.com/icssc/zotnfound-frontend/assets/93059380/f2a4f75e-9e98-4d01-8ee8-0025da531bbb)

## Resources
- [ZotNFound - Doc](https://docs.google.com/document/d/1UEuaNJaRmbvLXZJREeL5ARTRfXLX9acVglM9k8f0UbI/edit)
- [ZotNFound - DB Model](https://docs.google.com/document/d/11GNnXQYPDEzKQxUpPGkIm2GcPo4yAJErI0awGnJYpVE/edit?usp=sharing)
- [Chakra UI - Doc](https://chakra-ui.com/)
- [Chakra UI Modal](https://chakra-ui.com/docs/components/modal/usage)

**Comment by tyleryy** [comment]
I followed the steps setting up the frontend and backend to try to list an item. But they are not showing up on the map. Did I not set up the backend correctly or am I doing it incorrectly?

### Demo
https://github.com/icssc/zotnfound-frontend/assets/66880934/63343ee8-c683-41af-8943-09d53fe6890e

Also, is this normal?

### Server.js
![Screen Shot 2023-12-16 at 11 20 46 PM](https://github.com/icssc/zotnfound-frontend/assets/66880934/29690d82-e33a-4e97-8019-df436e42ba91)
