### ISSUE TITLE
List of Items Pagination

### ISSUE THREAD

**Issue by tyleryy** [icssc/zotnfound-frontend#47]
### Overview

The list of items in ZotnFound has grown too large--scroll length is too long and it takes a while to load all images. We should `paginate` the items in some way, meaning the user should only be able to see say the first 10 items and then be able to click to the next "page" of items to see the next 10. Like pages of Google after a search.

We could also potentially redesign how we present the items to users in some way to complement pagination.

Uploading Screen Recording 2024-02-27 at 7.56.20 PM.mov…

**Comment by NwinNwin** [comment]
<img width="407" alt="image" src="https://github.com/icssc/zotnfound-frontend/assets/93059380/a732f604-d0ed-424b-805b-7b687083dc4f">

# Make a `Load More` Button in `ResultBar.jsx`
- When the website first load, only 10 items show up
- `Load More` Button will load 10 more items.
- This avoid image to render all at once --> make website faster
