### ISSUE TITLE
Responsive Header

### ISSUE THREAD

**Issue by tyleryy** [icssc/zotnfound-frontend#50]
Responsiveness of the Header is slightly off after the moving of the `List Item Button` to the blue plus icon button.

user emblem dips slightly past the border
<img width="358" alt="Screenshot 2024-02-27 at 9 11 54 PM" src="https://github.com/icssc/zotnfound-frontend/assets/66880934/cb28459c-fbee-4aeb-9406-72d758a4a6bc">

near the breakpoint of the layout shift, the items are too close together (maybe flex or padding between them will fix it)
<img width="766" alt="Screenshot 2024-02-27 at 9 12 23 PM" src="https://github.com/icssc/zotnfound-frontend/assets/66880934/585ea36f-65dc-47ec-95a8-4cfc5d4f0c8d">

**Comment by NwinNwin** [comment]
<img width="1046" alt="image" src="https://github.com/icssc/zotnfound-frontend/assets/93059380/c14bcc5b-4617-47e7-9e64-9bcaf3158c72">

# Description:
- Work in `components/Home.jsx`
- Use inspect element to resize our page to test like the image above (let us know if you are stuck)
- Add breakpoints using [Chakra Responsive Styles](https://chakra-ui.com/docs/styled-system/responsive-styles) to fix this issue
# Resources
- [Chakra Responsive Styles](https://chakra-ui.com/docs/styled-system/responsive-styles)
